CREATE OR ALTER PROCEDURE MS_REGISTRA_NUEVO_CLIENTE (V_RFC VARCHAR(18), V_TIPO_PERSONA CHAR(1), V_CLAVE_REGIMEN_FISCAL CHAR(3), V_CLAVE_CLIENTE VARCHAR(20), V_NOMBRE VARCHAR(200))
AS
declare variable cliente_id integer;
declare variable cond_pago_id integer;
declare variable validacion_nombre integer;
declare variable validacion_rfc varchar(18);
declare variable validacion_rol int;
declare variable rol int;
begin

	:COND_PAGO_ID  = 866;
	
	SELECT CLIENTE_ID FROM CLIENTES WHERE NOMBRE = :V_NOMBRE INTO :VALIDACION_NOMBRE; 
	
	IF(:VALIDACION_NOMBRE IS NOT NULL) THEN --Si ya esta registrado el nombre del cliente
	BEGIN
		SELECT RFC_CURP FROM DIRS_CLIENTES WHERE CLIENTE_ID = :VALIDACION_NOMBRE INTO validacion_rfc;
		IF(validacion_rfc = :V_RFC) THEN --Si coincide el RFC
		BEGIN
			SELECT FIRST 1 ROL_CLAVE_CLI_ID FROM CLAVES_CLIENTES WHERE CLIENTE_ID = :VALIDACION_NOMBRE ORDER BY ROL_CLAVE_CLI_ID DESC INTO :VALIDACION_ROL; 
			
			IF(:VALIDACION_ROL <> 3 ) THEN
			BEGIN
				:ROL = :VALIDACION_ROL + 1; 
			END
			ELSE
			BEGIN
				:ROL = 1226;
			END
			
				
	
			INSERT INTO CLAVES_CLIENTES (CLAVE_CLIENTE_ID, CLAVE_CLIENTE, CLIENTE_ID, ROL_CLAVE_CLI_ID)
    		VALUES (-1, :V_CLAVE_CLIENTE, :V_NOMBRE, :ROL);
		END
		
		--Revisar si en este caso se modificara el nombre antes de insertarlo 
	END
	ELSE
	BEGIN
		INSERT INTO CLIENTES (CLIENTE_ID, NOMBRE, MONEDA_ID, COND_PAGO_ID, COBRAR_IMPUESTOS,
	    RETIENE_IMPUESTOS, SUJETO_IEPS, GENERAR_INTERESES, EMITIR_EDOCTA,LIMITE_CREDITO, 
	    USUARIO_CREADOR, FECHA_HORA_CREACION, USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF) 
    	VALUES (-1, :V_NOMBRE, 1, :COND_PAGO_ID, 'S', 'N', 'S', 'S','S', 0.0, 'SYSDBA', 
    	current_timestamp,'SYSDBA', current_timestamp);

    	SELECT FIRST 1 CLIENTE_ID FROM CLIENTES ORDER BY CLIENTE_ID DESC INTO :CLIENTE_ID;

    	INSERT INTO CLAVES_CLIENTES (CLAVE_CLIENTE_ID, CLAVE_CLIENTE, CLIENTE_ID, ROL_CLAVE_CLI_ID)
    	VALUES (-1, :V_CLAVE_CLIENTE, :CLIENTE_ID, 2);


    	INSERT INTO dirs_clientes (DIR_CLI_ID, CLIENTE_ID, NOMBRE_CONSIG, TIPO_PERSONA,  CLAVE_REGIMEN_FISCAL, ES_DIR_PPAL,
    	USAR_PARA_ENVIOS, USAR_PARA_FACTURAR, RFC_CURP) VALUES (
       -1 ,:CLIENTE_ID, 'Direcci?n principal', :V_TIPO_PERSONA, :V_CLAVE_REGIMEN_FISCAL, 'S', 'S', 'S', :V_RFC);	
	END
	
  suspend;
end