SET TERM ^ ;

create or alter procedure ms_devolucion_anticipo (
    v_nombre_xml varchar(100),
    v_nombre_cliente varchar(200),
    v_rfc_cliente varchar(13),
    v_folio_uso_fiscal numeric(15,2),
    v_xml blob sub_type 0 segment size 80,
    v_uuid varchar(60),
    v_impuesto_total numeric(15,2),
    v_importe_total numeric(15,2),
    v_cliente_id integer,
    v_fecha date,
    v_folio char(9))
returns (
    o_documento_insertado integer)
as
declare variable repositorio_id integer;
declare variable importe_id integer;
declare variable documento_id integer;
begin

:documento_id = GEN_ID(ID_DOCTOS,1);


INSERT INTO DOCTOS_CC (DOCTO_CC_ID, CONCEPTO_CC_ID, FOLIO, NATURALEZA_CONCEPTO, FECHA, HORA, CLAVE_CLIENTE, IMPORTE_COBRO, CLIENTE_ID, TIPO_CAMBIO,
CANCELADO, APLICADO, DESCRIPCION, LUGAR_EXPEDICION_ID, CUENTA_CONCEPTO, COBRADOR_ID, FORMA_EMITIDA, CONTABILIZADO, CONTABILIZADO_GYP, COND_PAGO_ID,
FECHA_DSCTO_PPAG, PCTJE_DSCTO_PPAG, FACTURA_MOSTRADOR, SISTEMA_ORIGEN, ESTATUS, ESTATUS_ANT, FECHA_APLICACION, ES_CFD, MODALIDAD_FACTURACION,
ENVIADO, FECHA_HORA_ENVIO, EMAIL_ENVIO, USO_CFDI, METODO_PAGO_SAT, INTEG_BA, CONTABILIZADO_BA, CUENTA_BAN_ID, REFER_MOVTO_BANCARIO,
USUARIO_CREADOR, FECHA_HORA_CREACION, USUARIO_AUT_CREACION, USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF, USUARIO_AUT_MODIF, USUARIO_CANCELACION,
FECHA_HORA_CANCELACION, USUARIO_AUT_CANCELACION,sucursal_id)
VALUES
(:documento_id, 27085, :V_FOLIO, 'C', :V_FECHA, current_time, 'PG', 0.0,:V_CLIENTE_ID, 1.0, 'N', 'S', NULL, 30076, null,  NULL, 'N', 'N', 'N', NULL, null,  0.0, NULL,
'CC', 'N', 'N', NULL, 'S', 'CFDI', 'N', NULL, NULL, 'S01', 'PUE', 'N', 'N', NULL, NULL, 'SYSDBA', null, 'SYSDBA', 'SYSDBA', null, 'SYSDBA', null,
null, NULL, 74375);

importe_id = GEN_ID(ID_DOCTOS,1);

INSERT INTO IMPORTES_DOCTOS_CC
(IMPTE_DOCTO_CC_ID, DOCTO_CC_ID, FECHA, CANCELADO, APLICADO, ESTATUS, TIPO_IMPTE, DOCTO_CC_ACR_ID, IMPORTE, IMPUESTO, IVA_RETENIDO, ISR_RETENIDO, DSCTO_PPAG, PCTJE_COMIS_COB)
VALUES
(:importe_id, :documento_id, current_date, 'N', 'S', 'N', 'T', :documento_id, :V_IMPORTE_TOTAL,  :V_IMPUESTO_TOTAL, 0, 0, 0, 0);

:repositorio_id = GEN_ID(ID_DOCTOS,1);

INSERT INTO REPOSITORIO_CFDI (CFDI_ID, MODALIDAD_FACTURACION, VERSION, UUID, NATURALEZA, TIPO_COMPROBANTE,
    TIPO_DOCTO_MSP, FOLIO, FECHA, RFC, TAXID, NOMBRE, IMPORTE, MONEDA, TIPO_CAMBIO, ES_PARCIALIDAD, NOM_ARCH,
    XML, REFER_GRUPO, FECHA_CANCELACION, SELLO_VALIDADO, USUARIO_VAL_SELLO, USUARIO_CREADOR, FECHA_HORA_CREACION,
    USUARIO_AUT_CREACION, USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF, USUARIO_AUT_MODIF)
VALUES
(:repositorio_id, 'CFDI', '3.3', :V_UUID, 'E', 'I', 'Devolucion Anticipo', 'TSTD100', CURRENT_DATE, :v_rfc_cliente, NULL, :V_NOMBRE_CLIENTE,
:v_importe_total + :v_impuesto_total, 'MXN', 0, 'N', :V_NOMBRE_XML, :V_XML, NULL, NULL, 'M', NULL, 'SYSDBA',current_timestamp, NULL, 'SYSDBA',
current_timestamp, NULL);


INSERT INTO USOS_FOLIOS_FISCALES
(USO_FOLIO_ID, FOLIOS_FISCALES_ID, FOLIO, FECHA, SISTEMA, DOCTO_ID, XML,  UUID, CFDI_ID )
VALUES
(-1, 781764, :v_folio_uso_fiscal, CURRENT_DATE, 'CC', :documento_id, :V_XML, :V_UUID, :repositorio_id)  ;

:O_DOCUMENTO_INSERTADO = documento_id;


  suspend;
end^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT USAGE ON SEQUENCE ID_DOCTOS TO PROCEDURE MS_DEVOLUCION_ANTICIPO;
GRANT INSERT ON DOCTOS_CC TO PROCEDURE MS_DEVOLUCION_ANTICIPO;
GRANT INSERT ON IMPORTES_DOCTOS_CC TO PROCEDURE MS_DEVOLUCION_ANTICIPO;
GRANT INSERT ON REPOSITORIO_CFDI TO PROCEDURE MS_DEVOLUCION_ANTICIPO;
GRANT INSERT ON USOS_FOLIOS_FISCALES TO PROCEDURE MS_DEVOLUCION_ANTICIPO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE MS_DEVOLUCION_ANTICIPO TO SYSDBA;