SET TERM ^ ;

create or alter procedure ms_crea_aplicacion_anticipo (
    v_docto_ins integer,
    v_xml blob sub_type 0 segment size 80,
    v_nom_xml varchar(50),
    v_nombre_cliente varchar(30),
    v_rfc varchar(18),
    v_uuid varchar(60),
    v_impuesto numeric(15,2),
    v_importe numeric(15,2),
    v_descripcion varchar(200),
    v_fecha date,
    v_folio char(9),
    v_cliente_id integer)
returns (
    aplicacion integer)
as
declare variable documento integer;
declare variable id_impuesto_iva integer;
declare variable pctj_iva numeric(15,2);
declare variable cfdiid integer;
declare variable docto_cc integer;
declare variable concepto_cc_id integer;
declare variable foliofiscalid integer;
declare variable impte_id integer;
declare variable consecutivo integer;
declare variable concepto_id integer;
declare variable clave_cliente varchar(20);
declare variable sucursal_id integer;
declare variable lugar_exp integer;
begin
  /* Procedure Text */

:SUCURSAL_ID =384;
:CONCEPTO_ID = 4;--27086;
:CONCEPTO_CC_ID = 183; --183;

SELECT FIRST 1 CC.CLAVE_CLIENTE FROM CLIENTES C
JOIN CLAVES_CLIENTES CC ON C.CLIENTE_ID = CC.CLIENTE_ID
WHERE C.CLIENTE_ID = :V_CLIENTE_ID AND CC.ROL_CLAVE_CLI_ID = 2 OR (C.CLIENTE_ID = :V_CLIENTE_ID) INTO :CLAVE_CLIENTE;

SELECT LE.LUGAR_EXPEDICION_ID FROM LUGARES_EXPEDICION LE WHERE LE.NOMBRE = 'Matriz' INTO :LUGAR_EXP;


SELECT CC.CONSECUTIVO FROM FOLIOS_CONCEPTOS CC
WHERE CC.CONCEPTO_ID = :CONCEPTO_ID AND CC.SISTEMA = 'CC' INTO :CONSECUTIVO;


UPDATE FOLIOS_CONCEPTOS CX SET CX.CONSECUTIVO = CX.CONSECUTIVO+1 WHERE
CX.CONCEPTO_ID = 11 AND CX.SISTEMA = 'CC' ;
    --Posiblemente tengamos que ambiar el concepto a 183
:DOCTO_CC = GEN_ID(ID_DOCTOS,1);
--Podemos calcular este ID para ahorrar recursos
INSERT INTO DOCTOS_CC (DOCTO_CC_ID, CONCEPTO_CC_ID, FOLIO, NATURALEZA_CONCEPTO, FECHA, HORA, CLAVE_CLIENTE, IMPORTE_COBRO, CLIENTE_ID, TIPO_CAMBIO, CANCELADO, APLICADO,
DESCRIPCION, LUGAR_EXPEDICION_ID, CUENTA_CONCEPTO, COBRADOR_ID, FORMA_EMITIDA, CONTABILIZADO, CONTABILIZADO_GYP, COND_PAGO_ID, FECHA_DSCTO_PPAG, PCTJE_DSCTO_PPAG,
FACTURA_MOSTRADOR, SISTEMA_ORIGEN, ESTATUS, ESTATUS_ANT, FECHA_APLICACION, ES_CFD, TIENE_ANTICIPO, MODALIDAD_FACTURACION, ENVIADO, FECHA_HORA_ENVIO, EMAIL_ENVIO, CFDI_CERTIFICADO,
USO_CFDI, METODO_PAGO_SAT, INTEG_BA, CONTABILIZADO_BA, CUENTA_BAN_ID, REFER_MOVTO_BANCARIO, USUARIO_CREADOR, FECHA_HORA_CREACION, USUARIO_AUT_CREACION, USUARIO_ULT_MODIF,
FECHA_HORA_ULT_MODIF, USUARIO_AUT_MODIF, USUARIO_CANCELACION, FECHA_HORA_CANCELACION, USUARIO_AUT_CANCELACION,sucursal_id)
VALUES(
:DOCTO_CC, :CONCEPTO_CC_ID, :V_FOLIO, 'R', :V_FECHA, current_time, :CLAVE_CLIENTE, 0, :V_CLIENTE_ID, 1, 'N', 'S', :V_DESCRIPCION, :LUGAR_EXP, NULL, NULL, 'N', 'N', 'N', NULL, NULL, 0,
NULL, 'CC', 'N', 'N', NULL, 'S', 'N', 'CFDI', 'N', current_timestamp, NULL, 'S', 'P01', 'PUE', 'N', 'N', NULL, NULL, 'SYSDBA', current_timestamp, NULL, 'SYSDBA', current_timestamp,
NULL, NULL, NULL, NULL, :SUCURSAL_ID);

INSERT INTO VENCIMIENTOS_CARGOS_CC (DOCTO_CC_ID, FECHA_VENCIMIENTO, PCTJE_VEN) VALUES (:DOCTO_CC, :V_FECHA, 100);

 --Creo que aqui se corrige el problema
INSERT INTO IMPORTES_DOCTOS_CC (IMPTE_DOCTO_CC_ID, DOCTO_CC_ID, FECHA, CANCELADO, APLICADO,
ESTATUS, TIPO_IMPTE, DOCTO_CC_ACR_ID, IMPORTE, IMPUESTO, IVA_RETENIDO, ISR_RETENIDO, DSCTO_PPAG,
PCTJE_COMIS_COB) VALUES (-1, :DOCTO_CC, :V_FECHA, 'N', 'S', 'N', 'R', :V_DOCTO_INS, 0, 0, 0, 0, 0, 0);

SELECT FIRST 1 IMPTE_DOCTO_CC_ID FROM IMPORTES_DOCTOS_CC SD ORDER BY IMPTE_DOCTO_CC_ID desc INTO :IMPTE_ID;
SELECT IMP.IMPUESTO_ID, PCTJE_IMPUESTO FROM IMPUESTOS IMP WHERE IMP.NOMBRE= 'IVA 16%' INTO :ID_IMPUESTO_IVA, :PCTJ_IVA ;

INSERT INTO IMPORTES_DOCTOS_CC_IMPTOS (IMPTE_DOCTO_CC_IMPTO_ID, IMPTE_DOCTO_CC_ID, IMPUESTO_ID,
IMPORTE, PCTJE_IMPUESTO, IMPUESTO) VALUES (-1, :IMPTE_ID, :ID_IMPUESTO_IVA, 0, :PCTJ_IVA, 0 );

  --Esta tabla define el importe que se tomara de cada anticipo
--INSERT INTO USOS_ANTICIPOS_CC (ANTICIPO_CC_ID, DOCTO_CC_ID, TIPO_USO, FECHA, IMPORTE, IMPUESTO, DOCTO_CC_ACR_ID, POR_DEPOSITAR, FECHA_HORA)
--VALUES (
--:V_ANTICIPO, :DOCTO_CC, 'P', :V_FECHA, 0, 0, :V_DOCTO_ACR, 'N', current_timestamp);

INSERT INTO REPOSITORIO_CFDI (CFDI_ID, MODALIDAD_FACTURACION, VERSION, UUID, NATURALEZA, TIPO_COMPROBANTE,
TIPO_DOCTO_MSP, FOLIO, FECHA, RFC, TAXID, NOMBRE, IMPORTE, MONEDA, TIPO_CAMBIO, ES_PARCIALIDAD, NOM_ARCH,
XML, REFER_GRUPO, FECHA_CANCELACION, SELLO_VALIDADO, USUARIO_VAL_SELLO, USUARIO_CREADOR, FECHA_HORA_CREACION,
USUARIO_AUT_CREACION, USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF, USUARIO_AUT_MODIF)
VALUES (
-1, 'CFDI', '3.3', :V_UUID, 'E', 'E', 'Aplicaciyn de anticipo',:consecutivo , :v_fecha, :V_RFC, NULL, :V_NOMBRE_CLIENTE, :V_IMPORTE + :V_IMPUESTO, 'MXN', 0, 'N',
:V_NOM_XML,:V_XML, NULL, NULL, 'M', NULL, 'SYSDBA', current_timestamp, NULL, 'SYSDBA', current_timestamp, NULL);



select first 1 r.cfdi_id from REPOSITORIO_CFDI r order by r.cfdi_id desc into :cfdiid;

select f.folios_fiscales_id from folios_fiscales f where f.serie='@' into :folioFiscalID;
--Cambiar la fecha y hora por la fecha y hora de timbrado
INSERT INTO USOS_FOLIOS_FISCALES (USO_FOLIO_ID, FOLIOS_FISCALES_ID, FOLIO, FECHA, SISTEMA, DOCTO_ID, XML,
PROV_CERT, FECHA_HORA_TIMBRADO, UUID, CFDI_ID) VALUES (-1, 215774, 00053, :v_fecha, 'CC',
:docto_cc, :V_XML, 'CDIGITAL', current_timestamp, :V_UUID,:cfdiid);

:APLICACION = :DOCTO_CC;

  suspend;
end^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT USAGE ON SEQUENCE ID_DOCTOS TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT ON CLIENTES TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT ON CLAVES_CLIENTES TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT ON LUGARES_EXPEDICION TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT,UPDATE ON FOLIOS_CONCEPTOS TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT INSERT ON DOCTOS_CC TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT INSERT ON VENCIMIENTOS_CARGOS_CC TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT,INSERT ON IMPORTES_DOCTOS_CC TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT ON IMPUESTOS TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT INSERT ON IMPORTES_DOCTOS_CC_IMPTOS TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT,INSERT ON REPOSITORIO_CFDI TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT SELECT ON FOLIOS_FISCALES TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;
GRANT INSERT ON USOS_FOLIOS_FISCALES TO PROCEDURE MS_CREA_APLICACION_ANTICIPO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE MS_CREA_APLICACION_ANTICIPO TO SYSDBA;