SET TERM ^ ;

create or alter procedure ms_agrega_art_ve (
    v_precio numeric(15,2),
    v_importe numeric(15,2),
    v_notas memo,
    v_unidades unidades_0,
    v_docto_ve_id integer,
    v_articulo_id varchar(30))
as
declare variable art_id integer;
declare variable precio_articulo importe_unitario;
declare variable renglon integer;
declare variable clave_articulo varchar(20);
begin
  /* Procedure Text */
select ARTICULO_ID FROM ARTICULOS WHERE  NOMBRE = UPPER(:V_ARTICULO_ID) INTO :ART_ID;
IF(:ART_ID IS NULL) THEN
BEGIN
  EXECUTE PROCEDURE MS_REGISTRA_NART(:V_ARTICULO_ID) RETURNING_VALUES :ART_ID;
END
--      SELECT ARTICULO_ID FROM claves_articulos WHERE  CLAVE_ARTICULO_ID = :V_ARTICULO_ID INTO :ART_ID;
SELECT PRECIO FROM PRECIOS_ARTICULOS WHERE ARTICULO_ID =  :ART_ID INTO :PRECIO_ARTICULO;
SELECT CLAVE_ARTICULO FROM GET_CLAVE_ART(:ART_ID) INTO :CLAVE_ARTICULO;

execute procedure gen_pos_reng_ve(V_DOCTO_VE_ID) RETURNING_VALUES :RENGLON;

INSERT INTO DOCTOS_VE_DET (
    DOCTO_VE_DET_ID, DOCTO_VE_ID, CLAVE_ARTICULO, ARTICULO_ID,  UNIDADES, UNIDADES_COMPROM,
    UNIDADES_SURT_DEV, PRECIO_UNITARIO, PCTJE_DSCTO,  PCTJE_DSCTO_CLI, PCTJE_DSCTO_VOL, PCTJE_DSCTO_PROMO,
    PRECIO_TOTAL_NETO, PCTJE_COMIS, ROL, NOTAS, POSICION
    ) VALUES (
-1, :V_DOCTO_VE_ID, :CLAVE_ARTICULO, :ART_ID, :V_UNIDADES, :V_UNIDADES, 0, :V_PRECIO, 0.0,  0.0, 0.0, 0.0,  :V_IMPORTE, 0.0, 'N', :V_NOTAS, :RENGLON);
--    -1, :V_DOCTO_VE_ID, :CLAVE_ARTICULO, :ART_ID, :V_UNIDADES, :V_UNIDADES, 0, :PRECIO_ARTICULO, 0.0,  0.0, 0.0, 0.0,  :PRECIO_ARTICULO * :V_UNIDADES, 0.0, 'N', :V_NOTAS, :RENGLON);

/*
SELECT CLIENTE_ID FROM doctos_ve WHERE DOCTO_VE_ID = :V_DOCTO_VE_ID INTO :CLIENTE;

INSERT INTO articulos_clientes (ART_CLI_ID, CLAVE_ARTICULO, ARTICULO_ID, CLIENTE_ID, CLAVE_ART_CLI, CAMPOS_ADDENDA)
VALUES(
    -1, :CLAVE_ARTICULO, :V_ARTICULO_ID, :CLIENTE, :CLAVE_ARTICULO, null)     */

  suspend;
end^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON ARTICULOS TO PROCEDURE MS_AGREGA_ART_VE;
GRANT EXECUTE ON PROCEDURE MS_REGISTRA_NART TO PROCEDURE MS_AGREGA_ART_VE;
GRANT SELECT ON PRECIOS_ARTICULOS TO PROCEDURE MS_AGREGA_ART_VE;
GRANT EXECUTE ON PROCEDURE GET_CLAVE_ART TO PROCEDURE MS_AGREGA_ART_VE;
GRANT EXECUTE ON PROCEDURE GEN_POS_RENG_VE TO PROCEDURE MS_AGREGA_ART_VE;
GRANT INSERT ON DOCTOS_VE_DET TO PROCEDURE MS_AGREGA_ART_VE;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE MS_AGREGA_ART_VE TO SYSDBA;