SET TERM ^ ;

create or alter procedure ms_registra_nart (
    v_articulo varchar(200))
returns (
    n_art_id integer)
as
declare variable art_id integer;
declare variable clave varchar(3);
begin
:ART_ID = GEN_ID(ID_DOCTOS,1);
INSERT INTO ARTICULOS (ARTICULO_ID, NOMBRE, ES_ALMACENABLE, ES_JUEGO, ESTATUS, IMPRIMIR_COMP, LINEA_ARTICULO_ID, UNIDAD_VENTA, UNIDAD_COMPRA, PESO_UNITARIO, ES_PESO_VARIABLE)
VALUES (:ART_ID, :V_ARTICULO, 'S', 'N', 'A', 'N', 1093,  'PZA', 'PZA', 1.0, 'N') ;
:CLAVE =  SUBSTRING(:V_ARTICULO FROM 1 FOR 3);
INSERT INTO CLAVES_ARTICULOS (CLAVE_ARTICULO_ID, CLAVE_ARTICULO, ARTICULO_ID, ROL_CLAVE_ART_ID, CONTENIDO_EMPAQUE )
VALUES (-1, 'MS'||:CLAVE, :ART_ID, 17, 1.0)  ;
:N_ART_ID = ART_ID;
  suspend;
end^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT USAGE ON SEQUENCE ID_DOCTOS TO PROCEDURE MS_REGISTRA_NART;
GRANT INSERT ON ARTICULOS TO PROCEDURE MS_REGISTRA_NART;
GRANT INSERT ON CLAVES_ARTICULOS TO PROCEDURE MS_REGISTRA_NART;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE MS_REGISTRA_NART TO SYSDBA;