/******************************************************************************/
/*                Genera el archivo en DOCTOS_VE                              */
/******************************************************************************/

/******************************************************************************/
/*                Generated by IBExpert 10/17/2025 2:45:48 AM                 */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CFDI_VENTAS_BASE (
    IDCFDIVENTAS           CHAR(50) NOT NULL,
    NORELACIONADOS         NUMERIC(5,0),
    SERIE                  VARCHAR(5),
    FOLIO                  NUMERIC(10,0),
    FECHAPROCESO           DATE,
    FECHATIMBRADO          TIMESTAMP,
    FECHAAPLICACION        DATE,
    NOCERTIFICADO          VARCHAR(20),
    CFDITIMBRADO           BLOB SUB_TYPE BINARY SEGMENT SIZE 80,
    UUIDSAT                CHAR(50),
    XMLCFDI                BLOB SUB_TYPE BINARY SEGMENT SIZE 80,
    ESTADO                 VARCHAR(7),
    RECEPTORNCOMERCIAL     VARCHAR(200),
    RECEPTORNOMBRE         VARCHAR(100),
    RECEPTORRFC            VARCHAR(50),
    RECEPTORDOMFISCAL      VARCHAR(10),
    RECEPTORREGFISCAL      VARCHAR(5),
    RECEPTORRFDESCRIPCION  VARCHAR(100),
    RECEPTORUSOCFDI        VARCHAR(5),
    RECEPTORUSODESC        VARCHAR(100),
    RECEPTOREMAIL          VARCHAR(100),
    TRASLADOIMPUESTO       VARCHAR(5),
    TRASLADOTIPOFACTOR     VARCHAR(6),
    TRASLADOTASAOCUOTA     VARCHAR(10),
    QRCODE                 VARCHAR(5000),
    CADENAORIGINALSAT      VARCHAR(2000),
    SELLOCFDI              VARCHAR(500),
    SELLOSAT               VARCHAR(500),
    CERTIFICADOSAT         VARCHAR(50),
    CERTIFICADOCFDI        VARCHAR(50),
    CORREOENVIADO          VARCHAR(6),
    CONSULTAENTITY         VARCHAR(5000),
    TOTAL                  NUMERIC(18,2),
    SUBTOTAL               NUMERIC(18,2),
    IMPUESTO               NUMERIC(18,2),
    TRASLADOBASE           VARCHAR(18),
    TRASLADOIMPORTE        VARCHAR(18),
    MPUESTOSTRASLADADOS    VARCHAR(18),
    FALTANTE               NUMERIC(18,2)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CFDI_VENTAS_BASE ADD CONSTRAINT PK_CFDIVENTASBASE PRIMARY KEY (IDCFDIVENTAS);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CFDI_VENTAS_BASE_BU0 */
CREATE OR ALTER TRIGGER CFDI_VENTAS_BASE_BU0 FOR CFDI_VENTAS_BASE
ACTIVE BEFORE UPDATE POSITION 0
AS
begin   /*
  execute PROCEDURE  MS_GENERA_DOCTO_VE(NEW.receptornombre,
NEW.folio, --Revisar
NEW.receptorncomercial || " " || current_date || "VENTA.XML",
NEW.uuidsat --Revisar,
NEW.xmlcfdi, --Revisar
3553,
NEW.xmlcfdi, --Revisar
NEW.uuidsat, --Revisar
NEW.IMPUESTO,
NEW.SUBTOTAL,
"VENTA" || NEW.receptorncomercial || current_date,
NEW.folio, --Revisar con Mar?a s esta bien que se use el mismo para la venta y para la aplicacion
NEW.consultaentity
)  */
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
