/******************************************************************************/
/*                Generated by IBExpert 10/17/2025 2:42:59 AM                 */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CFDI_VENTAS_AP_ANTICIPOS (
    ID                       CHAR(36) NOT NULL,
    ID_CFDI_VENTAS           CHAR(36) NOT NULL,
    FECHA_PROCESO            DATE NOT NULL,
    FECHA_TIMBRADO           TIMESTAMP NOT NULL,
    FECHA_APLICACION         DATE NOT NULL,
    CFDI_RESPUESTA_TIMBRADO  BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    UUID_SAT                 CHAR(36),
    XML_CFDI                 BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    ESTADO                   VARCHAR(50),
    NO_CERTIFICADO           VARCHAR(50),
    CADENA_ORIGINAL_SAT      BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    SELLO_CFDI               BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    SELLO_SAT                BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
    CERTIFICADO_SAT          VARCHAR(50),
    CERTIFICADO_CFDI         VARCHAR(50),
    QR_CODE                  VARCHAR(255),
    FOLIO                    VARCHAR(20)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CFDI_VENTAS_AP_ANTICIPOS ADD PRIMARY KEY (ID);


/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
