/******************************************************************************/
/*                Agrega los articulos a la venta                             */
/******************************************************************************/

/******************************************************************************/
/*                Generated by IBExpert 10/17/2025 2:47:48 AM                 */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CFDI_VENTAS_CONCEPTOS (
    IDLOCAL           CHAR(50) NOT NULL,
    IDCFDIVENTAS      VARCHAR(50) NOT NULL,
    CLAVEPRODSERV     VARCHAR(8),
    NOID              VARCHAR(100),
    CANTIDAD          VARCHAR(7),
    CLAVEUNIDAD       VARCHAR(20),
    UNIDAD            VARCHAR(40),
    DESCRIPCION       VARCHAR(999),
    VALORUNITARIO     VARCHAR(18),
    IMPORTE           VARCHAR(18),
    OBJETOIMP         VARCHAR(4),
    TRASLADOBASE      VARCHAR(18),
    TRASLADOIMPUESTO  VARCHAR(5),
    TRASLADOTFACTOR   VARCHAR(6),
    TRASLADOTCUOTA    VARCHAR(10),
    TRASLADOIMPORTE   VARCHAR(18),
    RECEPTORRFC       VARCHAR(100)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CFDI_VENTAS_CONCEPTOS ADD CONSTRAINT PK_CFDIVCONCEPTOS_ID PRIMARY KEY (IDLOCAL);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CFDI_VENTAS_CONCEPTOS_AU0 */
CREATE OR ALTER TRIGGER CFDI_VENTAS_CONCEPTOS_AU0 FOR CFDI_VENTAS_CONCEPTOS
ACTIVE AFTER UPDATE POSITION 0
AS
begin

       /*
  EXECUTE procedure MS_AGREGA_ART_VE(
  "", -- Revisar con Mar?a este valor
  NEW.CANTIDAD,
  NEW.IDCFDIVENTAS, --Cruzar UUID con repo
  NEW.CLAVEPRODSERV
  ) */
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
